# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "update"

  # Update npm packages
  - package-ecosystem: "npm"
    directory: "moni-moni/client/"
    schedule:
      interval: "daily"
    labels:
      - "npm update"

  # Update pip packages
  - package-ecosystem: "pip"
    directory: "moni-moni/server/"
    schedule:
      interval: "daily"
    labels:
      - "pip update"
