version: '3'

services:
  frontend:
    image: amalthundiyil/frontend:latest
    container_name: moni-moni-frontend
    build:
      context: './moni-moni/client'
      args:
        - REACT_APP_HOST=${REACT_APP_HOST}
        - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      main:


  backend:
    restart: always
    image: amalthundiyil/backend:latest
    container_name: moni-moni-backend
    command: gunicorn server.wsgi --bind 0.0.0.0:8000
    build:
      context: './moni-moni/server'
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_NAME}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      main:


  postgres:
    container_name: moni-moni-db
    build:
      context: ./moni-moni/db
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      main:


volumes:
  pgdata:


networks:
  main:
    driver: bridge
