apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: amalthundiyil/backend:1.0
          imagePullPolicy: Always
          command: ["gunicorn"]
          args: ["server.wsgi", "--bind", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PYTHONUNBUFFERED
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DEBUG
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_PORT
