name: Docker Compose Actions Workflow

on: push

jobs:

  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Test Backend
        run: docker run --network container:frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/
      - name: Test Frontend
        run: docker run --network container:backend appropriate/curl -s --retry 10 --retry-connrefused http://localhost/
